repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: deploy/.*
      - id: check-added-large-files
        args: ['--maxkb=100000']
      - id: check-json

  - repo: https://github.com/jazzband/pip-tools
    rev: 5.5.0
    hooks:
      - id: pip-compile
        files: requirements/requirements.in
        args:
          - requirements/requirements.in
      - id: pip-compile
        files: requirements/requirements(-test)?\.in
        args:
          - requirements/requirements.in
          - requirements/requirements-test.in
          - --output-file=requirements/requirements-test.txt

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      exclude: app/migrations/versions/.*

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
    - id: mypy
      args: [--no-strict-optional, --ignore-missing-imports]
